language: node_js
node_js:
  - "7"
  - "8"
script: npm run buildprod
cache:
  directories:
    - "node_modules"

sudo: required

services:
  - docker

before_install:
  - docker build -t worenga/nine-mens-morris-app .
  - docker run -d -p 127.0.0.1:8099:8099 worenga/nine-mens-morris-app
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push worenga/nine-mens-morris-app;
    fi
